web:
  build: web
  volumes:
    - web:/usr/src/app
  command: gunicorn -w 4 -b 0.0.0.0:1337 app:app

blog:
  image: dockerfile/ghost
  ports:
    - 2368:2368
  volumes:
    - ghost:/ghost-override

nginx:
  image: nginx:latest
  ports:
    - 80:80
    - 443:443
  links:
    - web:web
    - blog:blog
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf:ro